name: recorder
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  hexcolor: ^3.0.1
  shared_preferences: ^2.3.2
  speech_to_text: ^7.0.0
  sqflite: ^2.3.3+1
  web_socket_channel: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/unlogo.png